### ISSUE TITLE
Adding PC( Parallel Computing Lab) programs

### ISSUE THREAD

**Issue by manas11** [manas11/labprograms#7]
we need to complete the parallel computing lab programs and put it in this repository

**Comment by gauravahlawat81** [comment]
I take up this issue 
I will be adding programs of 11 september lab

**Comment by gauravahlawat81** [comment]
#8 will be the request for this issue

**Comment by VithikShah** [comment]
I take up this issue

**Comment by amangupta13** [comment]
I am taking this issue

**Comment by manas11** [comment]
This issue is to be  closed now
